### ISSUE TITLE
Make it possible to filter stack()

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-queues#16]
Right now `queues.stack()` returns a lot of data.

Some of this (DOM nodes I think) causes an exception when run in the devtools Chrome extension:

![image](https://user-images.githubusercontent.com/5851984/38642027-6079a1a0-3d9e-11e8-8183-a3b6ede9c85c.png)

I'm still investigating what exactly causes this, but to get around it I'd like to be able to do something like this:

```
can.queues.stack(function (task) {
    return {
        description: task.meta.stack.name + " ran task:" + task.fn.name
    };
})
```

**Comment by justinbmeyer** [comment]
I'm confused by what the problem here would be.  This is a problem using `postMessage` with the stack data or something?  

Why would `queues.stack()` need to provide this?  Can the dev tool run arbitrary code in the `user` realm?  Could it do this filtering before transmitting data?

It feels weird to add functionality like this to queues ...
